version: '3.9'
services:
  node:
    image: node:16
    command: "yarn dev"
    environment:
      HOST: 0.0.0.0
    ports:
        - "3000:3000"
    volumes:
        - .:/usr/src/app:cached
    working_dir: /usr/src/app